---
title: "Data exploration and  visualization"
subtitle: "Part 3"
output: github_document
---

```{r setup}
library(tidyverse)
#knitr::opts_chink$set(
 # fig.width = 6,
  #fig.asp = 0.6,
  #out.width = "90%"
#)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridus",
  ggplot2.continuous.fill = "viridus"
  )
#scale_color_discrete = scale_color_viridus_d
#scale_fill_discrete = scale_fill_viridus_d
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% 
  select(name, id, everything())

weather_df 
```


## `group_by`

```{r}
weather_df %>% 
  group_by(name, month)
```

## counting things
 
Count month observations

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(n_obs = n())
```

we can use `count()` as well

```{r}
weather_df %>% 
  count(name, month, name = "n_obs")
```

**Never** use base R's `table` function ! 


Other helpful counters 

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```


## Two by two tables 

```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE ~ ""
    )) %>% 
  group_by(name, cold) %>% 
  summarize(count = n())
```

```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE ~ ""
    )) %>% 
  janitor::tabyl(name, cold)
```

## General summaries 

You can do lots of summaries and this is a df so we can make a plot! 
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_prcp = mean(prcp, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE)
  ) 
```

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line()
```

Suppose we want to summarize many columns in the same place 

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(across(prcp:tmin, mean))
```

Reminder - sometimes data results are easier to read in other formats 

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name, 
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digits = 1)
```

